FROM ubuntu
#sem CACHED [2/4] RUN apt ....  
RUN apt update && apt install net-tools --yes && apt install vim --yes && apt install curl --yes

#com CACHED [2/4] RUN apt ....  
#RUN apt update
#RUN apt install net-tools --yes
#RUN apt install vim --yes
#RUN apt install curl --yes


